using DevOpsAIAgent.Core.Models;
using DevOpsAIAgent.Core.Interfaces.Services;
using DevOpsAIAgent.Core.Models.Configuration;
using Mscc.GenerativeAI;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging;

namespace DevOpsAIAgent.API.Services.LlmProviders;

/// <summary>
/// Google Gemini LLM provider implementation
/// </summary>
public class GeminiProvider : ILlmProvider
{
    private readonly GeminiConfiguration _config;
    private readonly ILogger<GeminiProvider> _logger;
    private readonly GoogleAI _googleAI;

    public string ProviderName => "Gemini";

    public GeminiProvider(IOptions<LlmConfiguration> options, ILogger<GeminiProvider> logger)
    {
        _config = options.Value.Gemini;
        _logger = logger;
        _googleAI = new GoogleAI(_config.ApiKey);
    }

    public async Task<AiAnalysis> GenerateDevOpsAnalysisAsync(string prompt, string context, long ciCdEventId = 0, CancellationToken cancellationToken = default)
    {
        try
        {
            var model = _googleAI.GenerativeModel(_config.Model);

            var fullPrompt = $@"
            You are a DevOps expert AI. Analyze the following context and provide insights for failure analysis and optimization.

            Context: {context}

            Analysis Request: {prompt}

            Please provide a comprehensive analysis including:
            1. Key findings and root cause analysis
            2. Specific recommendations for improvement
            3. Risk assessment and impact analysis
            4. Prioritized action items with timelines
            5. Prevention strategies for similar issues

            Respond in a structured, clear format that can be easily parsed and displayed in a dashboard.";

            var response = await model.GenerateContent(fullPrompt);
            var content = response?.Text ?? "No analysis generated";

            // Estimate token count (rough approximation)
            var tokenCount = EstimateTokenCount(fullPrompt) + EstimateTokenCount(content);

            return new AiAnalysis
            {
                // Id is auto-generated by database
                CiCdEventId = ciCdEventId,
                AnalysisText = content,
                GitDiff = ExtractGitDiffFromContext(context),
                ErrorLog = ExtractErrorLogFromContext(context),
                ModelUsed = $"{ProviderName}:{_config.Model}",
                TokensUsed = tokenCount,
                CreatedAt = DateTime.UtcNow
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating DevOps analysis with Gemini: {Error}", ex.Message);
            throw new InvalidOperationException($"Gemini analysis failed: {ex.Message}", ex);
        }
    }

    public async Task<string> GenerateCodeReviewAsync(string codeChanges, CancellationToken cancellationToken = default)
    {
        try
        {
            var model = _googleAI.GenerativeModel(_config.Model);

            var prompt = $@"
            Please perform a code review on the following changes:

            {codeChanges}

            Focus on:
            - Security vulnerabilities
            - Performance issues
            - Best practices
            - Code quality
            - Potential bugs

            Provide specific, actionable feedback.";

            var response = await model.GenerateContent(prompt);
            return response.Text ?? "No code review generated";
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating code review with Gemini");
            throw;
        }
    }

    public async Task<string> GenerateDeploymentRecommendationAsync(string deploymentContext, CancellationToken cancellationToken = default)
    {
        try
        {
            var model = _googleAI.GenerativeModel(_config.Model);

            var prompt = $@"
            Analyze the following deployment context and provide recommendations:

            {deploymentContext}

            Please provide:
            - Deployment strategy recommendations
            - Environment considerations
            - Rollback plan
            - Monitoring suggestions
            - Risk mitigation strategies";

            var response = await model.GenerateContent(prompt);
            return response.Text ?? "No deployment recommendation generated";
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating deployment recommendation with Gemini");
            throw;
        }
    }

    public async Task<string> GenerateCiCdAnalysisAsync(string pipelineData, CancellationToken cancellationToken = default)
    {
        try
        {
            var model = _googleAI.GenerativeModel(_config.Model);

            var prompt = $@"
            Analyze the following CI/CD pipeline data:

            {pipelineData}

            Please provide:
            - Pipeline performance analysis
            - Optimization recommendations
            - Failure point identification
            - Best practices suggestions
            - Security considerations";

            var response = await model.GenerateContent(prompt);
            return response.Text ?? "No CI/CD analysis generated";
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating CI/CD analysis with Gemini");
            throw;
        }
    }

    public async Task<bool> IsHealthyAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            if (string.IsNullOrEmpty(_config.ApiKey) || !_config.Enabled)
            {
                return false;
            }

            var model = _googleAI.GenerativeModel(_config.Model);
            var response = await model.GenerateContent("Hello");
            return !string.IsNullOrEmpty(response?.Text);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Gemini health check failed");
            return false;
        }
    }

    /// <summary>
    /// Estimate token count for text (rough approximation: 1 token ≈ 4 characters)
    /// </summary>
    private static int EstimateTokenCount(string text)
    {
        if (string.IsNullOrEmpty(text)) return 0;
        return (int)Math.Ceiling(text.Length / 4.0);
    }

    /// <summary>
    /// Extract git diff from context if present
    /// </summary>
    private static string? ExtractGitDiffFromContext(string context)
    {
        if (string.IsNullOrEmpty(context)) return null;

        // Look for git diff patterns
        var diffMarkers = new[] { "diff --git", "@@", "+++", "---" };
        if (diffMarkers.Any(marker => context.Contains(marker, StringComparison.OrdinalIgnoreCase)))
        {
            return context;
        }

        return null;
    }

    /// <summary>
    /// Extract error log from context if present
    /// </summary>
    private static string? ExtractErrorLogFromContext(string context)
    {
        if (string.IsNullOrEmpty(context)) return null;

        // Look for error patterns
        var errorMarkers = new[] { "error:", "exception:", "failed:", "stderr:", "stack trace:" };
        if (errorMarkers.Any(marker => context.Contains(marker, StringComparison.OrdinalIgnoreCase)))
        {
            return context;
        }

        return null;
    }
}