using DevOpsAIAgent.Core.Models;
using DevOpsAIAgent.Core.Interfaces.Services;
using DevOpsAIAgent.Core.Models.Configuration;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging;

namespace DevOpsAIAgent.API.Services.LlmProviders;

/// <summary>
/// OpenRouter LLM provider implementation
/// </summary>
public class OpenRouterProvider : ILlmProvider
{
    private readonly OpenRouterConfiguration _config;
    private readonly ILogger<OpenRouterProvider> _logger;
    private readonly IOpenRouterApi _api;

    public string ProviderName => "OpenRouter";

    public OpenRouterProvider(
        IOptions<LlmConfiguration> options,
        ILogger<OpenRouterProvider> logger,
        IOpenRouterApi api)
    {
        _config = options.Value.OpenRouter;
        _logger = logger;
        _api = api;
    }

    public async Task<AiAnalysis> GenerateDevOpsAnalysisAsync(string prompt, string context, long ciCdEventId = 0, CancellationToken cancellationToken = default)
    {
        try
        {
            var fullPrompt = $@"
            You are a DevOps expert AI. Analyze the following context and provide insights for failure analysis and optimization.

            Context: {context}

            Analysis Request: {prompt}

            Please provide a comprehensive analysis including:
            1. Key findings and root cause analysis
            2. Specific recommendations for improvement
            3. Risk assessment and impact analysis
            4. Prioritized action items with timelines
            5. Prevention strategies for similar issues

            Respond in a structured, clear format that can be easily parsed and displayed in a dashboard.";

            var request = new OpenRouterRequest
            {
                Model = _config.Model,
                Messages = new[]
                {
                    new OpenRouterMessage { Role = "user", Content = fullPrompt }
                },
                Temperature = _config.Temperature,
                MaxTokens = _config.MaxTokens
            };

            var response = await _api.CreateCompletionAsync(
                request,
                $"Bearer {_config.ApiKey}",
                "https://localhost",
                _config.AppName);

            var content = response.Choices?.FirstOrDefault()?.Message?.Content ?? "No analysis generated";
            var tokensUsed = response.Usage?.TotalTokens ?? EstimateTokenCount(fullPrompt + content);

            return new AiAnalysis
            {
                // Id is auto-generated by database
                CiCdEventId = ciCdEventId,
                AnalysisText = content,
                GitDiff = ExtractGitDiffFromContext(context),
                ErrorLog = ExtractErrorLogFromContext(context),
                ModelUsed = $"{ProviderName}:{_config.Model}",
                TokensUsed = tokensUsed,
                CreatedAt = DateTime.UtcNow
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating DevOps analysis with OpenRouter: {Error}", ex.Message);
            throw new InvalidOperationException($"OpenRouter analysis failed: {ex.Message}", ex);
        }
    }

    public async Task<string> GenerateCodeReviewAsync(string codeChanges, CancellationToken cancellationToken = default)
    {
        try
        {
            var prompt = $@"
            Please perform a code review on the following changes:

            {codeChanges}

            Focus on:
            - Security vulnerabilities
            - Performance issues
            - Best practices
            - Code quality
            - Potential bugs

            Provide specific, actionable feedback.";

            var request = new OpenRouterRequest
            {
                Model = _config.Model,
                Messages = new[]
                {
                    new OpenRouterMessage { Role = "user", Content = prompt }
                },
                Temperature = _config.Temperature,
                MaxTokens = _config.MaxTokens
            };

            var response = await _api.CreateCompletionAsync(
                request,
                $"Bearer {_config.ApiKey}",
                "https://localhost",
                _config.AppName);

            return response.Choices?.FirstOrDefault()?.Message?.Content ?? "No code review generated";
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating code review with OpenRouter");
            throw;
        }
    }

    public async Task<string> GenerateDeploymentRecommendationAsync(string deploymentContext, CancellationToken cancellationToken = default)
    {
        try
        {
            var prompt = $@"
            Analyze the following deployment context and provide recommendations:

            {deploymentContext}

            Please provide:
            - Deployment strategy recommendations
            - Environment considerations
            - Rollback plan
            - Monitoring suggestions
            - Risk mitigation strategies";

            var request = new OpenRouterRequest
            {
                Model = _config.Model,
                Messages = new[]
                {
                    new OpenRouterMessage { Role = "user", Content = prompt }
                },
                Temperature = _config.Temperature,
                MaxTokens = _config.MaxTokens
            };

            var response = await _api.CreateCompletionAsync(
                request,
                $"Bearer {_config.ApiKey}",
                "https://localhost",
                _config.AppName);

            return response.Choices?.FirstOrDefault()?.Message?.Content ?? "No deployment recommendation generated";
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating deployment recommendation with OpenRouter");
            throw;
        }
    }

    public async Task<string> GenerateCiCdAnalysisAsync(string pipelineData, CancellationToken cancellationToken = default)
    {
        try
        {
            var prompt = $@"
            Analyze the following CI/CD pipeline data:

            {pipelineData}

            Please provide:
            - Pipeline performance analysis
            - Optimization recommendations
            - Failure point identification
            - Best practices suggestions
            - Security considerations";

            var request = new OpenRouterRequest
            {
                Model = _config.Model,
                Messages = new[]
                {
                    new OpenRouterMessage { Role = "user", Content = prompt }
                },
                Temperature = _config.Temperature,
                MaxTokens = _config.MaxTokens
            };

            var response = await _api.CreateCompletionAsync(
                request,
                $"Bearer {_config.ApiKey}",
                "https://localhost",
                _config.AppName);

            return response.Choices?.FirstOrDefault()?.Message?.Content ?? "No CI/CD analysis generated";
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating CI/CD analysis with OpenRouter");
            throw;
        }
    }

    public async Task<bool> IsHealthyAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            if (string.IsNullOrEmpty(_config.ApiKey) || !_config.Enabled)
            {
                return false;
            }

            var request = new OpenRouterRequest
            {
                Model = _config.Model,
                Messages = new[]
                {
                    new OpenRouterMessage { Role = "user", Content = "Hello" }
                },
                Temperature = 0.1,
                MaxTokens = 10
            };

            var response = await _api.CreateCompletionAsync(
                request,
                $"Bearer {_config.ApiKey}",
                "https://localhost",
                _config.AppName);

            return response.Choices?.Any() == true;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "OpenRouter health check failed");
            return false;
        }
    }

    /// <summary>
    /// Estimate token count for text (rough approximation: 1 token ≈ 4 characters)
    /// </summary>
    private static int EstimateTokenCount(string text)
    {
        if (string.IsNullOrEmpty(text)) return 0;
        return (int)Math.Ceiling(text.Length / 4.0);
    }

    /// <summary>
    /// Extract git diff from context if present
    /// </summary>
    private static string? ExtractGitDiffFromContext(string context)
    {
        if (string.IsNullOrEmpty(context)) return null;

        // Look for git diff patterns
        var diffMarkers = new[] { "diff --git", "@@", "+++", "---" };
        if (diffMarkers.Any(marker => context.Contains(marker, StringComparison.OrdinalIgnoreCase)))
        {
            return context;
        }

        return null;
    }

    /// <summary>
    /// Extract error log from context if present
    /// </summary>
    private static string? ExtractErrorLogFromContext(string context)
    {
        if (string.IsNullOrEmpty(context)) return null;

        // Look for error patterns
        var errorMarkers = new[] { "error:", "exception:", "failed:", "stderr:", "stack trace:" };
        if (errorMarkers.Any(marker => context.Contains(marker, StringComparison.OrdinalIgnoreCase)))
        {
            return context;
        }

        return null;
    }
}